CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telefone VARCHAR(11) NOT NULL,
    senha VARCHAR(255),
    status_usuario INTEGER NOT NULL,
    tipo_usuario VARCHAR(255),
    CONSTRAINT uk_usuarios_cpf UNIQUE (cpf),
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT uk_usuarios_telefone UNIQUE (telefone)
);

CREATE TABLE IF NOT EXISTS livros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    autor VARCHAR(255) NOT NULL,
    isbn VARCHAR(255) NOT NULL,
    ano_lancamento INTEGER NOT NULL,
    is_disponivel BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_livros_isbn UNIQUE (isbn)
);

CREATE TABLE IF NOT EXISTS emprestimos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    livro_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    data_emprestimo DATE NOT NULL,
    data_prevista_devolucao DATE NOT NULL,
    data_devolucao DATE,
    status_emprestimo INTEGER NOT NULL,
    quantidade_renovacoes INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_emprestimos_livro FOREIGN KEY (livro_id) REFERENCES livros(id),
    CONSTRAINT fk_emprestimos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

CREATE TABLE IF NOT EXISTS reservas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    livro_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    data_emprestimo DATE,
    status_reserva SMALLINT,
    CONSTRAINT fk_reservas_livro FOREIGN KEY (livro_id) REFERENCES livros(id),
    CONSTRAINT fk_reservas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);
